INSERT INTO dp_class_accommodations(class_option) VALUES('Accessible Furniture');
INSERT INTO dp_class_accommodations(class_option) VALUES('Accessible Seating');
INSERT INTO dp_class_accommodations(class_option) VALUES('Preferential Seating');
INSERT INTO dp_class_accommodations(class_option) VALUES('Use of a Service Animal');
INSERT INTO dp_class_accommodations(class_option) VALUES('Use of a Recording Device');
INSERT INTO dp_class_accommodations(class_option) VALUES('Assistance Listening Technology');
INSERT INTO dp_class_accommodations(class_option) VALUES('Alternative Media');
INSERT INTO dp_class_accommodations(class_option) VALUES('Brailed Materials');
INSERT INTO dp_class_accommodations(class_option) VALUES('Reproductions of overheads, graphs, charts, powerpoint and/or notes');
INSERT INTO dp_class_accommodations(class_option) VALUES('Sign Language Interpreter/closed caption');
INSERT INTO dp_class_accommodations(class_option) VALUES('Written Instructions');
INSERT INTO dp_class_accommodations(class_option) VALUES('Oral Instructions');
INSERT INTO dp_class_accommodations(class_option) VALUES('No Grammar or Spelling Penalty');
INSERT INTO dp_class_accommodations(class_option) VALUES('Use of a Calculator');
INSERT INTO dp_class_accommodations(class_option) VALUES('Use of a Laptop');
INSERT INTO dp_class_accommodations(class_option) VALUES('Classroom Breaks as Needed');
INSERT INTO dp_class_accommodations(class_option) VALUES('Amended Attendance policy');
INSERT INTO dp_class_accommodations(class_option) VALUES('Extended time for in-class assignments');
INSERT INTO dp_class_accommodations(class_option) VALUES('Extended Time for post-syllabus assignments');
INSERT INTO dp_class_accommodations(class_option) VALUES('Closed Captioned Media');
INSERT INTO dp_class_accommodations(class_option) VALUES('Priority Registration ');
