INSERT INTO dp_disabilities(id,name) VALUES(0,'LD');
INSERT INTO dp_disabilities(id,name) VALUES(1,'HOH');
INSERT INTO dp_disabilities(id,name) VALUES(2,'Temp');
INSERT INTO dp_disabilities(id,name) VALUES(3,'Psych');
INSERT INTO dp_disabilities(id,name) VALUES(4,'Med');
INSERT INTO dp_disabilities(id,name) VALUES(5,'Visual');
INSERT INTO dp_disabilities(id,name) VALUES(6,'Speech');
INSERT INTO dp_disabilities(id,name) VALUES(7,'Ortho');
INSERT INTO dp_disabilities(id,name) VALUES(8,'Neuro');
INSERT INTO dp_disabilities(id,name) VALUES(9,'AD/HD');
INSERT INTO dp_disabilities(id,name) VALUES(10,'Brain Injury');
INSERT INTO dp_disabilities(id,name) VALUES(11,'Blind');
INSERT INTO dp_disabilities(id,name) VALUES(12,'Low Vision');
INSERT INTO dp_disabilities(id,name) VALUES(13,'Reading');
INSERT INTO dp_disabilities(id,name) VALUES(14,'Math');
INSERT INTO dp_disabilities(id,name) VALUES(15,'Language');
INSERT INTO dp_disabilities(id,name) VALUES(16,'Writing');
INSERT INTO dp_disabilities(id,name) VALUES(17,'Auditory');
INSERT INTO dp_disabilities(id,name) VALUES(18,'Physical');
INSERT INTO dp_disabilities(id,name) VALUES(19,'Autism Spectrum Disorders');
INSERT INTO dp_disabilities(id,name) VALUES(20,'Other');
