INSERT INTO dp_exam_accommodations(exam_option) VALUES('Reader');
INSERT INTO dp_exam_accommodations(exam_option) VALUES('Scribe');
INSERT INTO dp_exam_accommodations(exam_option) VALUES('Magnification Equipment');
INSERT INTO dp_exam_accommodations(exam_option) VALUES('Reduced Distraction Environment');
INSERT INTO dp_exam_accommodations(exam_option) VALUES('Calculator');
INSERT INTO dp_exam_accommodations(exam_option) VALUES('Computer');
INSERT INTO dp_exam_accommodations(exam_option) VALUES('Spell Checker');
INSERT INTO dp_exam_accommodations(exam_option) VALUES('Dictionary/Thesaurus');
INSERT INTO dp_exam_accommodations(exam_option) VALUES('Word Bank');
INSERT INTO dp_exam_accommodations(exam_option) VALUES('Exam Breaks');
INSERT INTO dp_exam_accommodations(exam_option) VALUES('Sign Language Interpreter');
INSERT INTO dp_exam_accommodations(exam_option) VALUES('Electronic Exams w/ Captions');
