INSERT INTO dp_majors(id,name) VALUES(1,'Other');
INSERT INTO dp_majors(id,name) VALUES(2,'Accounting');
INSERT INTO dp_majors(id,name) VALUES(3,'Economics');
INSERT INTO dp_majors(id,name) VALUES(4,'Basic');
INSERT INTO dp_majors(id,name) VALUES(5,'International');
INSERT INTO dp_majors(id,name) VALUES(6,'Finance');
INSERT INTO dp_majors(id,name) VALUES(7,'Management');
INSERT INTO dp_majors(id,name) VALUES(8,'Marketing');
INSERT INTO dp_majors(id,name) VALUES(9,'Athletic Training');
INSERT INTO dp_majors(id,name) VALUES(10,'Exercise, Sport and Health Education');
INSERT INTO dp_majors(id,name) VALUES(11,'Exercise and Sports Studies');
INSERT INTO dp_majors(id,name) VALUES(12,'Sports Medicine');
INSERT INTO dp_majors(id,name) VALUES(13,'Health Education and Health Promotion');
INSERT INTO dp_majors(id,name) VALUES(14,'Physical and Health Education');
INSERT INTO dp_majors(id,name) VALUES(15,'Commercial & Corporate Fitness');
INSERT INTO dp_majors(id,name) VALUES(16,'Fitness, Strength, & Conditioning');
INSERT INTO dp_majors(id,name) VALUES(17,'Sports Administration');
INSERT INTO dp_majors(id,name) VALUES(18,'Nutrition and Dietetics');
INSERT INTO dp_majors(id,name) VALUES(19,'Dietetics');
INSERT INTO dp_majors(id,name) VALUES(20,'Recreation, Parks and Tourism');
INSERT INTO dp_majors(id,name) VALUES(21,'Outdoor Recreation');
INSERT INTO dp_majors(id,name) VALUES(22,'Tourism and Recreation Management');
INSERT INTO dp_majors(id,name) VALUES(23,'Recreation Therapy');
INSERT INTO dp_majors(id,name) VALUES(24,'Teacher Education');
INSERT INTO dp_majors(id,name) VALUES(25,'Communication Sciences and Disorders');
INSERT INTO dp_majors(id,name) VALUES(26,'Nursing');
INSERT INTO dp_majors(id,name) VALUES(27,'Social Work');
INSERT INTO dp_majors(id,name) VALUES(28,'Criminal Justice');
INSERT INTO dp_majors(id,name) VALUES(29,'English');
INSERT INTO dp_majors(id,name) VALUES(30,'English Education*');
INSERT INTO dp_majors(id,name) VALUES(31,'Technical and Business Writing');
INSERT INTO dp_majors(id,name) VALUES(32,'Foreign Languages and Literatures');
INSERT INTO dp_majors(id,name) VALUES(33,'French');
INSERT INTO dp_majors(id,name) VALUES(34,'German');
INSERT INTO dp_majors(id,name) VALUES(35,'Spanish');
INSERT INTO dp_majors(id,name) VALUES(36,'History');
INSERT INTO dp_majors(id,name) VALUES(37,'History Education*');
INSERT INTO dp_majors(id,name) VALUES(38,'Interdisciplinary Studies');
INSERT INTO dp_majors(id,name) VALUES(39,'Early Childhood Education/Early Childhood Special Education with 5th year M.S. and licensure');
INSERT INTO dp_majors(id,name) VALUES(40,'Elementary Education');
INSERT INTO dp_majors(id,name) VALUES(41,'Liberal Arts - non-teaching');
INSERT INTO dp_majors(id,name) VALUES(42,'Special Education: Deaf and Hard of Hearing with licensure in Hearing Impairment');
INSERT INTO dp_majors(id,name) VALUES(43,'Special Education: General Curriculum with 5th year M.S. and licensure in ED, LD, & MR');
INSERT INTO dp_majors(id,name) VALUES(44,'Middle Education Licensure');
INSERT INTO dp_majors(id,name) VALUES(45,'Philosophy and Religious Studies');
INSERT INTO dp_majors(id,name) VALUES(46,'Philosophy');
INSERT INTO dp_majors(id,name) VALUES(47,'Religious Studies');
INSERT INTO dp_majors(id,name) VALUES(48,'Political Science');
INSERT INTO dp_majors(id,name) VALUES(49,'General');
INSERT INTO dp_majors(id,name) VALUES(50,'Public Administration & Public Service');
INSERT INTO dp_majors(id,name) VALUES(51,'Psychology');
INSERT INTO dp_majors(id,name) VALUES(52,'School of Communication');
INSERT INTO dp_majors(id,name) VALUES(53,'Communication');
INSERT INTO dp_majors(id,name) VALUES(54,'Corporate Communication & Public Advocacy');
INSERT INTO dp_majors(id,name) VALUES(55,'Public Relations');
INSERT INTO dp_majors(id,name) VALUES(56,'Media Studies');
INSERT INTO dp_majors(id,name) VALUES(57,'Advertising');
INSERT INTO dp_majors(id,name) VALUES(58,'Journalism');
INSERT INTO dp_majors(id,name) VALUES(59,'Production Technology');
INSERT INTO dp_majors(id,name) VALUES(60,'Web Design');
INSERT INTO dp_majors(id,name) VALUES(61,'Social Science');
INSERT INTO dp_majors(id,name) VALUES(62,'Sociology');
INSERT INTO dp_majors(id,name) VALUES(63,'Anthropological Sciences');
INSERT INTO dp_majors(id,name) VALUES(64,'Forensic Anthropology');
INSERT INTO dp_majors(id,name) VALUES(65,'Biology');
INSERT INTO dp_majors(id,name) VALUES(66,'Biology Education*');
INSERT INTO dp_majors(id,name) VALUES(67,'Biotechnology');
INSERT INTO dp_majors(id,name) VALUES(68,'Environmental Biology');
INSERT INTO dp_majors(id,name) VALUES(69,'General Biology');
INSERT INTO dp_majors(id,name) VALUES(70,'Medical Technology');
INSERT INTO dp_majors(id,name) VALUES(71,'Chemistry');
INSERT INTO dp_majors(id,name) VALUES(72,'Biochemistry');
INSERT INTO dp_majors(id,name) VALUES(73,'Chemistry Education*');
INSERT INTO dp_majors(id,name) VALUES(74,'Forensics');
INSERT INTO dp_majors(id,name) VALUES(75,'General Chemistry');
INSERT INTO dp_majors(id,name) VALUES(76,'Pre-Health Professional');
INSERT INTO dp_majors(id,name) VALUES(77,'Professional Chemist');
INSERT INTO dp_majors(id,name) VALUES(78,'Computer Science and Technology');
INSERT INTO dp_majors(id,name) VALUES(79,'Computer Science');
INSERT INTO dp_majors(id,name) VALUES(80,'Database');
INSERT INTO dp_majors(id,name) VALUES(81,'Networks');
INSERT INTO dp_majors(id,name) VALUES(82,'Software Engineering');
INSERT INTO dp_majors(id,name) VALUES(83,'Geology');
INSERT INTO dp_majors(id,name) VALUES(84,'Earth Sciences');
INSERT INTO dp_majors(id,name) VALUES(85,'Environmental and Engineering Geosciences');
INSERT INTO dp_majors(id,name) VALUES(86,'General Geology');
INSERT INTO dp_majors(id,name) VALUES(87,'Geospatial Science');
INSERT INTO dp_majors(id,name) VALUES(88,'Environmental');
INSERT INTO dp_majors(id,name) VALUES(89,'Geoinformatics');
INSERT INTO dp_majors(id,name) VALUES(90,'Information Science and Systems');
INSERT INTO dp_majors(id,name) VALUES(91,'Information Systems');
INSERT INTO dp_majors(id,name) VALUES(92,'Web Development');
INSERT INTO dp_majors(id,name) VALUES(93,'Mathematics');
INSERT INTO dp_majors(id,name) VALUES(94,'Applied Mathematics');
INSERT INTO dp_majors(id,name) VALUES(95,'Mathematics Education*');
INSERT INTO dp_majors(id,name) VALUES(96,'Statistics');
INSERT INTO dp_majors(id,name) VALUES(97,'Physics');
INSERT INTO dp_majors(id,name) VALUES(98,'Physical Science');
INSERT INTO dp_majors(id,name) VALUES(99,'Arts');
INSERT INTO dp_majors(id,name) VALUES(100,'Art');
INSERT INTO dp_majors(id,name) VALUES(101,'Art Education*');
INSERT INTO dp_majors(id,name) VALUES(102,'Art History and Museum Studies');
INSERT INTO dp_majors(id,name) VALUES(103,'Graphic Design');
INSERT INTO dp_majors(id,name) VALUES(104,'Studio');
INSERT INTO dp_majors(id,name) VALUES(105,'Dance');
INSERT INTO dp_majors(id,name) VALUES(106,'Design');
INSERT INTO dp_majors(id,name) VALUES(107,'Merchandising for Design');
INSERT INTO dp_majors(id,name) VALUES(108,'Design Management');
INSERT INTO dp_majors(id,name) VALUES(109,'Design Culture');
INSERT INTO dp_majors(id,name) VALUES(110,'Fashion Design');
INSERT INTO dp_majors(id,name) VALUES(111,'Interior Design');
INSERT INTO dp_majors(id,name) VALUES(112,'Music');
INSERT INTO dp_majors(id,name) VALUES(113,'Music');
INSERT INTO dp_majors(id,name) VALUES(114,'Music Business');
INSERT INTO dp_majors(id,name) VALUES(115,'Music Education');
INSERT INTO dp_majors(id,name) VALUES(116,'Music Therapy');
INSERT INTO dp_majors(id,name) VALUES(117,'Theatre');
